/**
 * @Description: index actions
 * @Created by ZiniTeam
 * @Date create: 16/11/2018
 */

/* CHECK NETWORK CONNECTION  */
export const CHECK_CONNECTION_STATUS = 'CHECK_CONNECTION_STATUS';
export const UPDATE_CONNECTION_STATUS = 'UPDATE_CONNECTION_STATUS';

/* CATEGORY TYPE */
export const GET_ALL_CATEGORY   = 'GET_ALL_CATEGORY';
export const REMOVE_ALL_CATEGORY   = 'REMOVE_ALL_CATEGORY';
/* CATEGORY TYPE */
export const GET_POST   = 'GET_POST';

export const SIDE_MENU_CHANGE = "SIDE_MENU_CHANGE"
export const REMOVE_SIDE_MENU   = 'REMOVE_SIDE_MENU';
/* ASYNC STORAGE BOOKMARK */
export const ASYNC_STORAGE_BOOKMARK = 'ASYNC_STORAGE_BOOKMARK';
export const REMOVE_ALL_BOOKMARK   = 'REMOVE_ALL_BOOKMARK';
/* SETTING */
export const FETCH_SETTINGS_SUCCESS = 'FETCH_SETTINGS_SUCCESS';
export const REMOVE_ALL_SETTING   = 'REMOVE_ALL_SETTING';
